[package]
name = "vidvault"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
opencv = "0.94.4"
serde = { version = "1.0.219", features = ["derive"] }
youtube_dl = { version = "0.8.0", features = ["downloader"] }
